export class Country {
  constructor(public name: string) {}
}

export const countryList = [
  new Country('中国'),
  new Country('韩国'),
  new Country('日本'),
  new Country('加拿大'),
  new Country('美国'),
  new Country('墨西哥'),
  new Country('危地马拉'),
  new Country('古巴'),
  new Country('哥斯达黎加'),
  new Country('哥伦比亚'),
  new Country('秘鲁'),
  new Country('玻利维亚'),
  new Country('巴西'),
  new Country('智利'),
  new Country('阿根廷'),
  new Country('新西兰'),
  new Country('澳大利亚'),
  new Country('印度尼西亚'),
  new Country('新加坡'),
  new Country('泰国'),
  new Country('缅甸'),
  new Country('印度'),
  new Country('巴基斯坦'),
  new Country('阿富汗'),
  new Country('伊朗'),
  new Country('伊拉克'),
  new Country('沙特阿拉伯'),
  new Country('埃及'),
  new Country('索马里'),
  new Country('坦桑尼亚'),
  new Country('马达加斯加'),
  new Country('津巴布韦'),
  new Country('南非'),
  new Country('刚果'),
  new Country('尼日利亚'),
  new Country('利比亚'),
  new Country('摩洛哥'),
  new Country('西班牙'),
  new Country('法国'),
  new Country('意大利'),
  new Country('希腊'),
  new Country('德国'),
  new Country('英国'),
  new Country('挪威'),
  new Country('波兰'),
  new Country('瑞典'),
  new Country('芬兰'),
  new Country('白俄罗斯'),
  new Country('乌克兰'),
  new Country('土耳其'),
  new Country('哈萨克斯坦'),
  new Country('俄罗斯'),
  new Country('蒙古'),
];
